# -*- coding: utf-8 -*-
"""png_2_mat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tcYnwnVwMpxc6-xL-9qHiwYDkM5tYSza
"""

import os
import numpy as np
import matplotlib.pyplot as plt 
import cv2
import scipy.io as sio
from scipy.io import loadmat

supervisely_mask_list = os.listdir('/home/user/Desktop/full_n_final/supervisely_cleaned_masks')
print(len(supervisely_mask_list))

print(type(mask_list[0]))
mask_list[0]


def read_mask(img_path): #, input_sz=(224, 224)):
    """
    Read image file and return cropped, resized, intensity-normalized array
        Arguments
            :img_path: str
            :crop_specs: list
            :input_sz: tuple
        Output
            :rgb_norm: numpy array
    """
    bgr = cv2.imread(img_path)
    rgb = bgr[:,:,::-1]
    # if len(crop_specs) == 4:
    #     rgb = rgb[ crop_specs[0]:crop_specs[1], crop_specs[2]:crop_specs[3], :]
    # rgb = cv2.resize(rgb, (600, 800))
    # rgb = cv2.resize(rgb, input_sz)
    rgb_norm = rgb.astype(np.float32)/ 255.
    
    return rgb_norm

try: 

    # creating a folder named data 
    if not os.path.exists('/content/drive/My Drive/png_2_mat'): 
        os.makedirs('/content/drive/My Drive/png_2_mat') 

# if not created then raise error 
except OSError: 
    print ('Error: Creating directory of mat_mask')

i = 0
for name in mask_list:
  path = '/content/drive/My Drive/png_masks/' + name
  # path = '/content/'+name
  mask = read_mask(path)
  mask = mask[:,:,0]>0.5
  id = name.split('.')
  sio.savemat('/content/drive/My Drive/png_2_mat/'+str(id[0])+'_mask'+'.mat', {'mask':mask})
  i+=1
  if i%50==0:
    print(i, 'Files downloaded...')
print('Total {} files downloaded successfully'.format(i))

from scipy.io import loadmat
mat = loadmat('/content/mat_mask/00001_mask.mat')
mask = mat['mask']

print(np.amax(mask), np.amin(mask))

print(mask.dtype)

mask.shape

mask_list = os.listdir('/content/drive/My Drive/images')
# mask_list = ['00001.png']
print(len(mask_list))
import os

rmv = {}
for name in mask_list:
  if name in rmv.keys():
    rmv[name]+=1
  else:
    rmv[name] = 1
for name in rmv.keys():
  if rmv[name] > 1:
    print(name)

# extra = ['000000415001 (1).jpg', '000000279117 (1).jpg', '000000272253 (1).jpg', '000000416524 (1).jpg', 
# '000000405982 (1).jpg', '000000537211 (1).jpg', '000000405401 (1).jpg']
# for ex in extra:
#   if ex in mask_list:
#     os.remove('/content/drive/My Drive/images/'+ex)
#     print('removed')

